### ISSUE TITLE
TypeError: Cannot read property 'allContentfulBlogPost' of undefined

### ISSUE THREAD

**Issue by MaximumCrash** [moonmeister/gatsby-contentful-netlify-example#1]
Hello, 
I was recently introduced to your example and I think it's fantastic! 

I seem to have run into a build issue right after createLayouts that states an undefined issue. The complete output looks like: 

`error Cannot read property 'allContentfulBlogPost' of undefined

  TypeError: Cannot read property 'allContentfulBlogPost' of undefined
  
  - gatsby-node.js:18 graphql.then.result
    /Users/rtaylorfoster/gcn-test/gatsby-node.js:18:18
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:606 Promise._settlePromiseCtx
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:138 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  
  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
  

error UNHANDLED REJECTION`

**Comment by moonmeister** [comment]
Hello! So, when you access contentful data the property names are based on the data you create in contentful. aka "allContentful<Content Type>", in my case, it was "BlogPost". Make sure you've named your data type accordingly in contentful. If not you can update the graphql queries to use the correct content type name. Also you can use [graphiql](http://localhost:8000/___graphql) in your dev environment to explore the contentful data as seen by Gatsby. 

If you haven't done gatsby's getting started tutorials they'll give you the tools to understand everything. https://www.gatsbyjs.org/tutorial/

The other option is you haven't set your contentful api keys. This repo sets them via environment variable as not to expose my keys to the public. Make sure you replace those in the `gatsby-config.js` or set those in your env.

These are the possible issues I can think of, let me know if you have any other questions.

**Comment by MaximumCrash** [comment]
Thank you for replying so quickly. It was definitely how my Contentful content was named. I just have to change up how graphql views the data types.
